# Generated by Django 6.0 on 2026-01-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ihi', models.TextField(db_column='IHI', primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.TextField()),
                ('home_number', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.TextField()),
                ('emergency_contact_phone', models.TextField()),
                ('date_registered', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('date_of_birth', models.DateTimeField()),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
