# Generated by Django 6.0 on 2026-01-10 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_hired', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'nurse',
                'managed': False,
            },
        ),
    ]
