# Generated by Django 6.0 on 2026-01-22 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.TextField()),
                ('room_type', models.TextField()),
                ('floor', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
    ]
