# Generated by Django 6.0 on 2026-01-22 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted_at', models.DateField(default=django.utils.timezone.now)),
                ('discharged_at', models.DateField(default=django.utils.timezone.now)),
                ('admission_reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'admission',
                'managed': False,
            },
        ),
    ]
